# --------------------
# Define arguments.
# --------------------

# ==================== Alas ====================

Scheduler:
  Enable: false
  NextRun: 2020-01-01 00:00:00
  Command: Alas
  SuccessInterval: 0
  FailureInterval: 120
  ServerUpdate: 00:00
Emulator:
  Serial: 127.0.0.1:5555
  PackageName: com.bilibili.azurlane
  Server:
    value: cn
    option: [cn, en, jp, tw]
  ScreenshotMethod:
    value: ADB
    option: [ADB, uiautomator2, aScreenCap]
  ControlMethod:
    value: minitouch
    option: [ADB, uiautomator2, minitouch]
Error:
  HandleError: true
  SaveError: true
  ScreenshotLength: 1
Optimization:
  CombatScreenshotInterval: 1.0
  TaskHoardingDuration: 0
  CloseGameDuringWait: false
DropRecord:
  SaveFolder: ./screenshots
  AzurStatsID: null
  SaveResearch: false
  UploadResearch: false
  SaveCommission: false
  UploadCommission: false
  SaveCombat: false
Retirement:
  Enable: true
  RetireMode:
    value: one_click_retire
    option: [one_click_retire, enhance, old_retire]
  RetireAmount:
    value: retire_all
    option: [retire_all, retire_10]
  EnhanceFavourite: false
  EnhanceFilter:
  EnhanceCheckPerCategory: 2
  OldRetireN: true
  OldRetireR: true
  OldRetireSR: false
  OldRetireSSR: false

# ==================== Farm ====================

Campaign:
  Name: 7-2
  Event:
    value: campaign_main
    option: [campaign_main]
  Mode:
    value: normal
    option: [normal, hard]
  UseClearMode: true
  UseFleetLock: true
  UseAutoSearch: false
  Use2xBook: false
  AmbushEvade: true
StopCondition:
  RunCount: 0
  OilLimit: 1000
  MapAchievement:
    value: non_stop
    option: [non_stop, 100_percent_clear, map_3_stars, threat_safe, threat_safe_without_3_stars]
  StageIncrease: false
  GetNewShip: false
  ReachLevel120: false
Fleet:
  Fleet1:
    value: 1
    option: [1, 2, 3, 4, 5, 6]
  Fleet1Formation:
    value: double_line
    option: [line_ahead, double_line, diamond]
  Fleet1Mode:
    value: combat_auto
    option: [combat_auto, combat_manual, stand_still_in_the_middle, hide_in_bottom_left]
  Fleet1Step:
    value: 3
    option: [2, 3, 4, 5]
  Fleet2:
    value: 2
    option: [0, 1, 2, 3, 4, 5, 6]
  Fleet2Formation:
    value: double_line
    option: [line_ahead, double_line, diamond]
  Fleet2Mode:
    value: combat_auto
    option: [combat_auto, combat_manual, stand_still_in_the_middle, hide_in_bottom_left]
  Fleet2Step:
    value: 2
    option: [2, 3, 4, 5]
  FleetOrder:
    value: fleet1_mob_fleet2_boss
    option: [fleet1_mob_fleet2_boss, fleet1_boss_fleet2_mob, fleet1_all_fleet2_standby, fleet1_standby_fleet2_all]
  AutoSearchFleetOrder:
    value: fleet1_mob_fleet2_boss
    option: [fleet1_mob_fleet2_boss, fleet1_boss_fleet2_mob, fleet1_all_fleet2_standby, fleet1_standby_fleet2_all]
Submarine:
  Fleet:
    value: 0
    option: [0, 1, 2]
  Mode:
    value: do_not_use
    option: [do_not_use, hunt_only, every_combat]
Emotion:
  CalculateEmotion: true
  IgnoreLowEmotionWarn: false
  Fleet1Value: 119
  Fleet1Record: 2020-01-01 00:00:00
  Fleet1Control:
    value: prevent_yellow_face
    option: [keep_exp_bonus, prevent_green_face, prevent_yellow_face, prevent_red_face]
  Fleet1Recover:
    value: not_in_dormitory
    option: [not_in_dormitory, dormitory_floor_1, dormitory_floor_2]
  Fleet1Oath: false
  Fleet2Value: 119
  Fleet2Record: 2020-01-01 00:00:00
  Fleet2Control:
    value: prevent_yellow_face
    option: [keep_exp_bonus, prevent_green_face, prevent_yellow_face, prevent_red_face]
  Fleet2Recover:
    value: not_in_dormitory
    option: [not_in_dormitory, dormitory_floor_1, dormitory_floor_2]
  Fleet2Oath: false
HpControl:
  UseHpBalance: false
  UseEmergencyRepair: false
  UseLowHpRetreat: false
  HpBalanceThreshold: 0.2
  HpBalanceWeight: 1000, 1000, 1000
  RepairUseSingleThreshold: 0.3
  RepairUseMultiThreshold: 0.6
  LowHpRetreatThreshold: 0.3
Raid:
  Mode:
    value: hard
    option: [easy, normal, hard]
  UseTicket: false
C11AffinityFarming:
  RunCount: 32
C72MysteryFarming:
  StepOnA3: true
C122MediumLeveling:
  LargeEnemyTolerance:
    value: 1
    option: [0, 1, 2, 10]
C124LargeLeveling:
  NonLargeEnterTolerance:
    value: 1
    option: [0, 1, 2]
  NonLargeRetreatTolerance:
    value: 1
    option: [0, 1, 2, 10]
  PickupAmmo:
    value: 3
    option: [3, 4, 5]
GemsFarming:
  FlagshipChange: true
  FlagshipEquipChange: false
  VanguardChange: false
  VanguardEquipChange: false
  LowEmotionRetreat: true
  CommonCV:
    value: any
    option: [any, langley, bogue, ranger, hermes]

# ==================== Reward ====================

Commission:
  DoMajorCommission: false
  CommissionFilter: |-
    DailyEvent
    > Gem-8 > Gem-4 > Gem-2
    > NightDrill-8 > NightDrill-7 > NightDrill-6
    > ExtraDrill-0:20 > ExtraDrill-1 > ExtraDrill-2 > ExtraDrill-3 > ExtraDrill-3:20 > ExtraDrill-5:20
    > Box-6 > Box-3 > Box-1
    > DailyCube-0:30 > UrgentCube-1:30 > DailyCube-1:30 > UrgentCube-1:45 > UrgentCube-2:15 > UrgentCube-3
    > Major
    > DailyChip > DailyResource
    > UrgentBook-2:30 > UrgentBook-2 > UrgentBook-1:20 > UrgentBook-1:40
    > Daily-0:20 > Daily-0:30 > Daily-1:00 > Daily-1:30 > Daily-2:00
    > NightOil > NightCube
    > shortest
Tactical:
  TacticalFilter: |-
    SameT4 > SameT3 > SameT2 > SameT1
    > BlueT2 > YellowT2 > RedT2
    > BlueT3 > YellowT3 > RedT3
    > BlueT4 > YellowT4 > RedT4
    > BlueT1 > YellowT1 > RedT1
    > first
Research:
  UseCube: false
  UseCoin: true
  UsePart: true
  PresetFilter:
    value: series_4
    option:
      - custom
      - series_4
      - series_3
      - series_3_than_2
  CustomFilter: |-
    S4-Q0.5 > Q-0.5 > S4-DR0.5 > S4-H0.5 > S4-PRY0.5 > DR-0.5 > PRY-0.5
    > S4-Q4 > S4-Q2 > S4-Q1
    > S4-DR2.5 > S4-PRY2.5
    > S4-G1.5 > S4-G2.5
    > S4-DR5 > S4-PRY5
    > S4-G4 > S4-DR8
    > S4-1 > S4-2 > S4-4 > reset > shortest
Dorm:
  Collect: true
  Feed: true
  FeedFilter: 20000 > 10000 > 5000 > 3000 > 2000 > 1000
Meowfficer:
  BuyAmount: 1
  TrainMeowfficer: false
  FortChoreMeowfficer: true
GuildLogistics:
  Enable: true
  ExchangeFilter: |-
    PlateTorpedoT1 > PlateAntiAirT1 > PlatePlaneT1 > PlateGunT1 > PlateGeneralT1
    > PlateTorpedoT2 > PlateAntiAirT2 > PlatePlaneT2 > PlateGunT2 > PlateGeneralT2
    > PlateTorpedoT3 > PlateAntiAirT3 > PlatePlaneT3 > PlateGunT3 > PlateGeneralT3
    > OxyCola > Coolant > Merit > Coin > Oil
GuildOperation:
  Enable: true
  JoinThreshold: 1
  AttackBoss: true
  BossFleetRecommend: false
Reward:
  CollectOil: true
  CollectCoin: true
  CollectExp: true
  CollectMission: true
GeneralShop:
  UseGems: false
  Refresh: false
  Filter: |-
    BookRedT3 > BookYellowT3 > BookBlueT3 > BookRedT2
    > Cube
    > FoodT6 > FoodT5
GuildShop:
  Refresh: true
  Filter: |-
    PlateT4 > BookT3 > PRBP > CatT3 > Chip > BookT2 > Retrofit > FoodT6 > FoodT5 > CatT2 > BoxT4
  BOX_T3:
    value: ironblood
    option: [eagle, royal, sakura, ironblood]
  BOX_T4:
    value: ironblood
    option: [eagle, royal, sakura, ironblood]
  BOOK_T2:
    value: red
    option: [red, blue, yellow]
  BOOK_T3:
    value: red
    option: [red, blue, yellow]
  RETROFIT_T2:
    value: cl
    option: [dd, cl, bb, cv]
  RETROFIT_T3:
    value: cl
    option: [dd, cl, bb, cv]
  PLATE_T2:
    value: general
    option: [general, gun, torpedo, antiair, plane]
  PLATE_T3:
    value: general
    option: [general, gun, torpedo, antiair, plane]
  PLATE_T4:
    value: gun
    option: [general, gun, torpedo, antiair, plane]
  PR1:
    value: neptune
    option: [neptune, monarch, ibuki, izumo, roon, saintlouis]
  PR2:
    value: seattle
    option: [seattle, georgia, kitakaze, gascogne]
  PR3:
    value: cheshire
    option: [cheshire, mainz, odin, champagne]
MedalShop:
  Filter: |-
    DRBP > PRBP
    > BookRedT3 > BookYellowT3 > BookBlueT3 > BookRedT2 > BookYellowT2 > BookBlueT2
    > RetrofitT3 > PlateGeneralT3
    > FoodT6 > FoodT5
MeritShop:
  Refresh: false
  Filter: |-
    Cube
Shipyard:
  ResearchSeries: 1
  ShipIndex: 0
  BuyAmount: 2
Gacha:
  Pool:
    value: light
    option: [light, heavy, special, event, wishing_well]
  Amount:
    value: 1
    option: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  UseDrill: false

# ==================== Daily ====================

Daily:
  UseDailySkip: true
  EscortMission:
    value: first
    option: [skip, first, second, third]
  EscortMissionFleet:
    value: 5
    option: [1, 2, 3, 4, 5, 6]
  AdvanceMission:
    value: first
    option: [skip, first, second, third]
  AdvanceMissionFleet:
    value: 5
    option: [1, 2, 3, 4, 5, 6]
  FierceAssault:
    value: first
    option: [skip, first, second, third]
  FierceAssaultFleet:
    value: 5
    option: [1, 2, 3, 4, 5, 6]
  TacticalTraining:
    value: second
    option: [skip, first, second, third]
  TacticalTrainingFleet:
    value: 5
    option: [1, 2, 3, 4, 5, 6]
  SupplyLineDisruption:
    value: second
    option: [skip, first, second, third]
Hard:
  HardStage: 11-4
  HardFleet:
    value: 1
    option: [1, 2]
Exercise:
  OpponentChooseMode:
    value: max_exp
    option: [max_exp, easiest, leftmost, easiest_else_exp]
  OpponentTrial: 1
  ExercisePreserve: 0
  LowHpThreshold: 0.4
  LowHpConfirmWait: 0.1
  OpponentRefreshValue: 0
  OpponentRefreshRecord: 2020-01-01 00:00:00
Sos:
  Chapter:
    value: 3
    option: [3, 4, 5, 6, 7, 8, 9, 10]
EventAb:
  StageFilter: |-
    A1 > A2 > A3 > B1 > B2 > B3
  LastStage: 0
RaidDaily:
  StageFilter: |-
    hard > normal > easy

# ==================== Opsi ====================

OpsiAshAssist:
  Tier: 15
OpsiGeneral:
  AshAttack: true
  BuyActionPoint: false
  OilLimit: 1000
  RepairThreshold: 0.4
  BuyAkashiShop: true
  AkashiShopFilter: |-
    ActionPoint > PurpleCoins
OpsiExplore:
  SpecialRadar: false
  LastZone: 0
OpsiDaily:
  BuySupply: true
  DoMission: true
OpsiObscure:
  UseLogger: true
  CallSubmarine: true
  ForceRun: false
OpsiMeowfficerFarming:
  ActionPointPreserve: 500
  HazardLevel:
    value: 5
    option: [1, 2, 3, 4, 5, 6]
  TargetZone:
    value: 0

# ==================== Tools ====================

Daemon:
  EnterMap: true
OpsiDaemon:
  RepairShip: true
Benchmark:
  TestScreenshotMethod: true
  TestClickMethod: true
AzurLaneUncensored:
  Repository: https://gitee.com/LmeSzinc/AzurLaneUncensored
